### ISSUE TITLE
Ver 2 todo list 

### ISSUE THREAD

**Issue by hanneskod** [hanneskod/classtools#12]
- [ ] Let’s not be finder-centric when creating `ClassLoader` objects. 
- [ ] `ClassLoader` could be a psr-11 compatible container..
- [ ] Move some methods from `ClassLoaderInterface` to `FilterInterface`. The current setup does not pass static analysis. 
- [ ] Iterate over `ClassDefinition` objects instead of `ReflectionClass`. Better encapsulation. 
- [ ] Develop the `where` filter.
